<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <Compile Remove="Checks/**/*.cs" />
    <ProjectReference Include="../../../shared/Dwsg.Shared.csproj" />
    <ProjectReference Include="../Generals/Dwsg.Generals.csproj" />
    <Compile Include="../World/**/*.cs" Exclude="../World/Checks/**/*.cs" />
  </ItemGroup>
</Project>
